version: '3.8'

services:
    covid_vaccine_server_nginx:
        build: docker/nginx
        image: semsa/covid_vaccine_server_nginx:latest
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            # - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
            #- ./nginx/logs:/var/www/app/logs
        container_name: covid_vaccine_server_nginx
        depends_on:
        - covid_vaccine_server_php
        
    covid_vaccine_server_php:
        build:
            context: .
            cache_from:
                - vendor
        image: semsa/covid_vaccine_server_php:latest
        expose:
            - 9000
        volumes:
            # - composer-cache:/composer/cache
            - .:/var/www
            - ./logs:/var/www/logs
            # - ./nginx/conf.d/:/etc/nginx/conf.d/
        container_name: covid_vaccine_server_php

networks:
  default:
      external: 
          name: docker-semsa